import express from "express";
import axios from "axios";
import fs from "fs";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

app.set("view engine", "ejs");
app.set("views", "./views");

app.use(express.urlencoded({ extended: true }));
app.use(express.static("public"));

const apiKey = process.env.API_KEY;

// Load groupedData.json (generated by your convert.js script)
const groupedData = JSON.parse(fs.readFileSync("public/groupedData.json", "utf-8"));

// Flatten all cities into one array for validation
const allCities = Object.values(groupedData).flat().map(c => c.toLowerCase());

app.get("/", (req, res) => {
  res.render("index.ejs");
});

app.post("/check", async (req, res) => {
  const { city } = req.body;

  // Validate city exists
  if (!allCities.includes(city.toLowerCase())) {
    return res.render("index.ejs", { error: `City "${city}" not found in database` });
  }

  try {
    const datum = await axios.get("https://api.weatherapi.com/v1/current.json", {
      params: { key: apiKey, q: city, aqi: "yes" },
    });

    const result = datum.data;
    res.render("index.ejs", { result });
  } catch (error) {
    console.error("Error fetching weather data:", error.message);
    res.render("index.ejs", { error: "Could not fetch weather data" });
  }
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
